INSERT INTO CART VALUES ( 1 );
INSERT INTO CART VALUES ( 2 );
INSERT INTO CART VALUES ( 3 );
INSERT INTO CART VALUES ( 4 );
INSERT INTO CART VALUES ( 5 );

INSERT INTO CUSTOMER(CUSTOMER_ID, CUSTOMER_NAME, ADDRESS, PHONE_NO, CART_ID) VALUES (1, 'Nguyễn Văn A', 'TP.HCM', '0123456789', 1);
INSERT INTO CUSTOMER(CUSTOMER_ID, CUSTOMER_NAME, ADDRESS, PHONE_NO, CART_ID) VALUES (2, 'Trần Văn B', 'Hà Nội', '0987654321', 2);
INSERT INTO CUSTOMER(CUSTOMER_ID, CUSTOMER_NAME, ADDRESS, PHONE_NO, CART_ID) VALUES (3, 'Lê Thị C', 'Nghệ An', '0789123456', 3);
INSERT INTO CUSTOMER(CUSTOMER_ID, CUSTOMER_NAME, ADDRESS, PHONE_NO, CART_ID) VALUES (4, 'Hồ Quang D', 'Nam Định', '0369258147', 4);
INSERT INTO CUSTOMER(CUSTOMER_ID, CUSTOMER_NAME, ADDRESS, PHONE_NO, CART_ID) VALUES (5, 'Võ Hồng E', 'Cà Mau', '0159372468', 5);

INSERT INTO PRODUCT VALUES ( 1, 'Áo Marvel', 'Nam', 'L', 100000 );
INSERT INTO PRODUCT VALUES ( 2, 'Áo Marvel', 'Nam', 'XL', 110000 );
INSERT INTO PRODUCT VALUES ( 3, 'Áo Marvel', 'Nam', 'XXL', 125000 );
INSERT INTO PRODUCT VALUES ( 4, 'Chân váy đen', 'Nữ', 'M', 150000 );
INSERT INTO PRODUCT VALUES ( 5, 'Chân váy đen', 'Nữ', 'L', 170000 );
INSERT INTO PRODUCT VALUES ( 6, 'Đầm đen dài', 'Nữ', 'M', 200000 );
INSERT INTO PRODUCT VALUES ( 7, 'Đầm đen dài', 'Nữ', 'L', 230000 );
INSERT INTO PRODUCT VALUES ( 8, 'Đầm đen dài', 'Nữ', 'XL', 250000 );
INSERT INTO PRODUCT VALUES ( 9, 'Quần Jean xanh', 'Nam', '40', 210000 );
INSERT INTO PRODUCT VALUES ( 10, 'Quần Jean xanh', 'Nam', '45', 240000 );