CREATE TABLE CART
(
    CART_ID INT NOT NULL PRIMARY KEY
);

CREATE TABLE PRODUCT
(
    PRODUCT_ID INT NOT NULL PRIMARY KEY,
    NAME_PRODUCT VARCHAR(100) NOT NULL,
    TYPE CHAR(3),
    SIZE CHAR(3),
    PRICE DECIMAL NOT NULL
);

CREATE TABLE CUSTOMER
(
    CUSTOMER_ID INT NOT NULL PRIMARY KEY,
    CUSTOMER_NAME NVARCHAR(50) NOT NULL,
    ADDRESS NVARCHAR(100),
    PHONE_NO CHAR(20) NOT NULL,
    CART_ID INT,
    FOREIGN KEY (CART_ID) REFERENCES CART(CART_ID)
);

CREATE TABLE CART_ITEM
(
    CART_ID INT NOT NULL,
    PRODUCT_ID INT NOT NULL,
    QUANTITY_WISHED INT NOT NULL,
    DATE_ADDED DATE NOT NULL,
    TOTAL_AMOUNT DECIMAL NOT NULL,
    FOREIGN KEY (CART_ID) REFERENCES CART(CART_ID),
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID),
    PRIMARY KEY (CART_ID, PRODUCT_ID)
);
